class HealthLabel < ApplicationRecord
  has_many :dish_health_labels, dependent: :destroy
  has_many :dishes, through: :dish_health_labels
  has_many :diet_profiles, dependent: :destroy

  enum name: { alcohol_free: "Alcohol-Free",
               celery_free: "Celery-Free",
               crustacean_free: "Crustacean-Free",
               dash: "DASH",
               dairy_free: "Dairy-Free",
               egg_free: "Egg-Free",
               fodmap_free: "FODMAP-Free",
               fish_free: "Fish-Free",
               gluten_free: "Gluten-Free",
               immuno_supportive: "Immuno-Supportive",
               keto_friendly: "Keto-Friendly",
               kidney_friendly: "Kidney-Friendly",
               kosher: "Kosher",
               low_potassium: "Low Potassium",
               low_sugar: "Low Sugar",
               lupine_free: "Lupine-Free",
               mediterranean: "Mediterranean",
               mollusk_free: "Mollusk-Free",
               mustard_free: "Mustard-Free",
               no_oil_added: "No oil added",
               paleo: "Paleo",
               peanut_free: "Peanut-Free",
               pescatarian: "Pescatarian",
               pork_free: "Pork-Free",
               red_meat: "Red-Meat",
               red_meat_free: "Red-Meat-Free",
               sesame_free: "Sesame-Free",
               shellfish_free: "Shellfish-Free",
               soy_free: "Soy-Free",
               sugar_conscious: "Sugar-Conscious",
               sulfite_free: "Sulfite-Free",
               tree_nut: "Tree-Nut",
               tree_nut_free: "Tree-Nut-Free",
               vegan: "Vegan",
               vegetarian: "Vegetarian",
               wheat_free: "Wheat-Free" }
end
